version: '3'
services:
  db:
    image: "mysql:5.7.19"
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: scyigisawesome
      MYSQL_DATABASE: scyig
      MYSQL_USER: scyig
      MYSQL_PASSWORD: scyig
